# K-means

Tenemos que definir el número de clusters a priori

Elegimos k clusters basándonos en lo que creamos necesario e inicializamos sus centroides (de manera aleatoria o siguiendo algún criterio...).<br>
A continuación asignamos cada punto del dataset al cluster cuyo centroide sea más cercano.
Luego recalculariamos los clusters y volveriamos al paso anterior (hasta que ningún punto sea reasignado a otro cluster).<br>
El objetivo es minimizar las distancias intracluster:

$$ SS_w(C_j) = \sum_{x \in C_j}{(x - c_j) ^ 2} $$

También podemos usar la distancia intracluster normalizada:

$$ S\widetilde{S}_w(C_j) = \sum_{j = 1}^{k}{\frac{SS_W(C_j)}{SS_T}} $$

donde

$$ SS_T = \sum_{i = 1}^{n}{(x_i - \overline{x})^2} $$

In [7]:
import numpy as np

data = np.random.randn(90).reshape(30, 3)
data

array([[  4.32679726e-01,  -2.99256015e-01,  -1.29067553e+00],
       [ -7.88202014e-01,  -7.06723976e-01,   1.30410309e-02],
       [ -8.01814247e-01,  -2.13703434e-01,   4.85374371e-01],
       [  1.64116505e-01,  -1.21603191e+00,   9.43688470e-01],
       [ -5.32190003e-01,  -2.13987365e+00,  -1.34398275e+00],
       [ -8.25105514e-01,  -5.12209770e-01,  -1.20441678e+00],
       [  3.06395364e-01,  -6.47702632e-01,   8.22542487e-01],
       [  1.43004178e+00,  -1.16751975e+00,   1.11338154e+00],
       [  3.31917457e-01,  -6.42323466e-01,  -3.29338743e-01],
       [  7.18338601e-01,  -2.33472267e-01,   1.27524296e-01],
       [ -2.62174382e-02,  -1.92659715e-01,  -1.73952602e+00],
       [ -2.25425651e+00,   1.90291330e-01,   2.69114236e+00],
       [  2.06976571e+00,  -5.60469635e-01,  -1.33819118e+00],
       [ -2.56569356e+00,   8.91670735e-01,   6.97717576e-01],
       [  2.97785083e-01,   2.69580342e-01,   8.52806685e-03],
       [  2.01970888e+00,  -1.33786019e-01,  -7.8849137

In [49]:
#Decidimos que haya 2 clusters por ejemplo y elegimos aleatoriamente sus coordenadas
c1 = np.random.choice(range(len(data)))
c2 = np.random.choice(range(len(data)))
centers = np.vstack([data[c1], data[c2]])
centers

array([[ 0.78354571, -2.23456109, -0.22757788],
       [-0.82510551, -0.51220977, -1.20441678]])

In [50]:
from scipy.cluster.vq import vq

vq(data, centers)
#Esta función dados unos centros dice a que cluster pertenece cada punto 
#y la distancia intracluster entre los puntos y centros

(array([1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0,
        0, 1, 1, 1, 1, 1, 1], dtype=int32),
 array([ 1.27859829,  1.23345092,  1.71611266,  1.67121485,  1.65968909,
         0.        ,  1.96177089,  1.83158581,  1.45650036,  2.03339765,
         1.01325036,  4.20848683,  2.38545719,  2.93575243,  1.82847321,
         2.50119556,  2.34733869,  0.94284606,  0.        ,  0.92105787,
         0.98480083,  1.93001459,  1.2816728 ,  2.58387835,  2.78236212,
         2.11432635,  1.07356324,  2.63872844,  1.81863115,  1.13862903]))

In [52]:
from scipy.cluster.vq import kmeans

kmeans(data, centers)
#Esto calcula los centros y el ultimo número indica la suma de los cuadrados

(array([[ 0.83778117, -0.93861621,  0.10907747],
        [-0.75069601, -0.30961799, -0.3469408 ]]), 1.4527224451794629)

In [53]:
#En lugar de inicializar los centros podemos simplemente decirle el número de clusters que queremos
kmeans(data, 2)

(array([[ 0.23336328, -0.55681212, -0.88335959],
        [-0.57314357, -0.62600786,  1.11853143]]), 1.3833375988817094)